package org.kikd.azure.resources.backend

import org.kikd.azure.azure
import org.kikd.azure.resources.api.AzureResource
import org.kikd.azure.resources.api.AzureStack
import org.kikd.azure.resources.api.InfraParameter
import org.kikd.azure.resources.api.infrastructure
import org.kikd.azure.resources.ir.AzureInfraResource
import org.kikd.azure.resources.ir.AzureTerraformIrCompiler
import org.kikd.azure.resources.ir.AzureTerraformIrContext
import org.kikd.azure.resources.ir.AzureTerraformResourceSpec
import org.kikd.azure.resources.render.azureFileSlug
import org.kikd.azure.resources.render.escapeHcl
import org.kikd.core.GeneratedFile
import org.kikd.core.KikdProjectPlan
import org.kikd.core.PlanAwareGeneratorBackend

class AzureTerraformBackend(
    private val directory: String = "infra",
) : PlanAwareGeneratorBackend {
    override val id: String = "azure-terraform"
    private val compiler = AzureTerraformIrCompiler()

    override fun generate(plan: KikdProjectPlan): List<GeneratedFile> {
        val infrastructure = plan.project.azure()?.infrastructure()?.model ?: return emptyList()
        val allResources = infrastructure.stacks.flatMap { it.resources }
        val stackSpecs = infrastructure.stacks.flatMap { stack ->
            val context = AzureTerraformIrContext(stack, allResources)
            stack.resources.map { resource ->
                val infraResource = resource as? AzureInfraResource
                    ?: backendCapabilityError(resource, "Terraform", "AzureInfraResource")
                val spec = infraResource.terraformSpec(context)
                    ?: backendSpecError(resource, "Terraform")
                StackTerraformSpec(stack, spec)
            }
        }

        val files = mutableListOf(GeneratedFile("$directory/provider.tf", renderProvider()))
        if (stackSpecs.any { it.spec.requiresClientConfig }) {
            files += GeneratedFile("$directory/data.tf", "data \"azurerm_client_config\" \"current\" {}")
        }

        val stackVariables = infrastructure.stacks.flatMap { it.parameters }.distinctBy { it.name }
        if (stackVariables.isNotEmpty()) {
            files += GeneratedFile("$directory/variables.tf", renderVariables(stackVariables))
        }

        val includeStackName = infrastructure.stacks.size > 1
        stackSpecs.forEach { stackSpec ->
            files += GeneratedFile(
                "$directory/${terraformFileName(stackSpec.stack.name, stackSpec.spec, includeStackName)}",
                compiler.renderResource(stackSpec.spec),
            )
        }
        return files.sortedBy { it.relativePath }
    }

    private fun renderProvider(): String = buildString {
        appendLine("terraform {")
        appendLine("  required_providers {")
        appendLine("    azurerm = {")
        appendLine("      source  = \"hashicorp/azurerm\"")
        appendLine("      version = \"~> 3.0\"")
        appendLine("    }")
        appendLine("  }")
        appendLine("}")
        appendLine()
        appendLine("provider \"azurerm\" {")
        appendLine("  features {}")
        appendLine("}")
    }.trimEnd()

    private fun renderVariables(variables: List<InfraParameter>): String = buildString {
        variables.forEach { param ->
            appendLine("variable \"${param.name}\" {")
            appendLine("  type = ${terraformType(param.type)}")
            if (param.defaultValue != null) {
                appendLine("  default = ${terraformValue(param.defaultValue)}")
            }
            appendLine("}")
            appendLine()
        }
    }.trimEnd()

    private fun terraformType(type: String): String = when (type) {
        "string" -> "string"
        "int", "integer" -> "number"
        "bool", "boolean" -> "bool"
        else -> type
    }

    private fun terraformValue(value: Any): String = when (value) {
        is String -> "\"${value.escapeHcl()}\""
        is Number -> value.toString()
        is Boolean -> value.toString()
        else -> "\"${value.toString().escapeHcl()}\""
    }

    private fun terraformFileName(
        stackName: String,
        spec: AzureTerraformResourceSpec,
        includeStackName: Boolean,
    ): String {
        val prefix = if (includeStackName) "${azureFileSlug(stackName)}-" else ""
        val type = spec.type.value.removePrefix("azurerm_")
        return "$prefix${azureFileSlug(type)}-${azureFileSlug(spec.logicalName)}.tf"
    }

    private fun backendCapabilityError(resource: AzureResource, backend: String, capability: String): Nothing =
        error("Resource '${resource.logicalName}' (${resource::class.qualifiedName}) cannot be generated by $backend because it does not implement $capability.")

    private fun backendSpecError(resource: AzureResource, backend: String): Nothing =
        error("Resource '${resource.logicalName}' (${resource::class.qualifiedName}) cannot be generated by $backend because it does not provide $backend IR.")

    private data class StackTerraformSpec(
        val stack: AzureStack,
        val spec: AzureTerraformResourceSpec,
    )
}
