package org.kikd.azure.resources.backend

import org.kikd.azure.azure
import org.kikd.azure.resources.api.InfraParameter
import org.kikd.azure.resources.api.AzureResource
import org.kikd.azure.resources.api.AzureStack
import org.kikd.azure.resources.api.infrastructure
import org.kikd.azure.resources.ir.AzureBicepIrCompiler
import org.kikd.azure.resources.ir.AzureBicepIrContext
import org.kikd.azure.resources.ir.AzureInfraResource
import org.kikd.azure.resources.render.azureSymbol
import org.kikd.core.GeneratedFile
import org.kikd.core.KikdProjectPlan
import org.kikd.core.PlanAwareGeneratorBackend

class AzureBicepBackend(
    private val directory: String = "infra",
) : PlanAwareGeneratorBackend {
    override val id: String = "azure-bicep"
    private val compiler = AzureBicepIrCompiler()

    override fun generate(plan: KikdProjectPlan): List<GeneratedFile> {
        val infrastructure = plan.project.azure()?.infrastructure()?.model ?: return emptyList()
        return listOf(
            GeneratedFile("$directory/main.bicep", renderMain(infrastructure.stacks)),
            GeneratedFile("$directory/main.bicepparam", renderParameters(infrastructure.stacks)),
        )
    }

    private fun renderMain(stacks: List<AzureStack>): String = buildString {
        val locationParameters = locationParameters(stacks)
        appendLine("targetScope = 'subscription'")
        appendLine()
        locationParameters.values.forEach { appendLine("param $it string") }
        stackParameters(stacks).forEach { appendLine(renderParameterDeclaration(it)) }
        if (locationParameters.isNotEmpty() || stacks.any { it.parameters.isNotEmpty() }) appendLine()

        val allResources = stacks.flatMap { it.resources }
        stacks.forEach { stack ->
            val context = AzureBicepIrContext(
                stack = stack,
                allResources = allResources,
                locationParameter = locationParameters.getValue(stack.name),
            )
            stack.resources.forEach { resource ->
                val infraResource = resource as? AzureInfraResource
                    ?: backendCapabilityError(resource, "Bicep", "AzureInfraResource")
                val spec = infraResource.bicepSpec(context)
                    ?: backendSpecError(resource, "Bicep")
                appendLine(compiler.renderResource(spec))
                appendLine()
            }
        }
    }.trimEnd()

    private fun renderParameters(stacks: List<AzureStack>): String = buildString {
        appendLine("using './main.bicep'")
        locationParameters(stacks).forEach { (stackName, parameterName) ->
            val stack = stacks.single { it.name == stackName }
            appendLine("param $parameterName = ${compiler.renderParameterValue(stack.location)}")
        }
        stackParameters(stacks).forEach { param ->
            val envVarName = param.name.uppercase()
            val defaultPart = param.defaultValue?.let { ", ${renderParameterValue(it)}" } ?: ""
            appendLine("param ${param.name} = readEnvironmentVariable('$envVarName'$defaultPart)")
        }
    }.trimEnd()

    private fun locationParameters(stacks: List<AzureStack>): Map<String, String> =
        stacks.associate { stack ->
            stack.name to if (stacks.size == 1) "location" else "${azureSymbol(stack.name)}Location"
        }

    private fun stackParameters(stacks: List<AzureStack>): List<InfraParameter> =
        stacks.flatMap { it.parameters }.distinctBy { it.name }

    private fun renderParameterDeclaration(param: InfraParameter): String =
        "param ${param.name} ${param.type}${param.defaultValue?.let { " = ${renderParameterValue(it)}" } ?: ""}"

    private fun renderParameterValue(value: Any): String = when (value) {
        is String -> compiler.renderParameterValue(value)
        is Number -> value.toString()
        is Boolean -> value.toString()
        else -> compiler.renderParameterValue(value.toString())
    }

    private fun backendCapabilityError(resource: AzureResource, backend: String, capability: String): Nothing =
        error("Resource '${resource.logicalName}' (${resource::class.qualifiedName}) cannot be generated by $backend because it does not implement $capability.")

    private fun backendSpecError(resource: AzureResource, backend: String): Nothing =
        error("Resource '${resource.logicalName}' (${resource::class.qualifiedName}) cannot be generated by $backend because it does not provide $backend IR.")
}
